/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apple-v1.glb --transform 
Files: apple-v1.glb [1.21MB] > /Users/kingstonkoh/Desktop/r3f-webpage/fruits/public/apple-v1-transformed.glb [80.98KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/apple-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['apple_low_obj_Material_#35_0'].geometry} material={materials.Material_35} position={[-13.564, 3.711, -4.175]} rotation={[-1.419, 0.11, 1.892]} />
    </group>
  )
}

useGLTF.preload('/apple-v1-transformed.glb')
